-- ============================================================
-- C1 FIX: Full schema.sql rewrite — matches live database
-- ============================================================
-- The original schema.sql was missing 5 entire tables and had
-- wrong column names on data_analyses. This file is the
-- authoritative schema for disaster recovery / staging setup.
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── profiles ─────────────────────────────────────────────────
-- Core user table. One row per auth.users entry.
CREATE TABLE IF NOT EXISTS profiles (
  id                        uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email                     text NOT NULL,
  subscription_tier         text NOT NULL DEFAULT 'free' CHECK (subscription_tier IN ('free', 'elite')),
  is_admin                  boolean NOT NULL DEFAULT false,
  bypass_stripe             boolean NOT NULL DEFAULT false,
  stripe_customer_id        text,
  stripe_subscription_id    text,
  education_badge_earned    boolean NOT NULL DEFAULT false,
  education_badge_earned_at timestamptz,
  education_completion_pct  integer NOT NULL DEFAULT 0,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users read own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "users update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "service role full access profiles" ON profiles
  USING (auth.role() = 'service_role');

-- ── account_settings ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS account_settings (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id         uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
  account_balance numeric NOT NULL DEFAULT 10000,
  risk_percent    numeric NOT NULL DEFAULT 1,
  htf_bias_lock   text NOT NULL DEFAULT 'OFF' CHECK (htf_bias_lock IN ('BULLISH', 'BEARISH', 'OFF')),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE account_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users manage own settings" ON account_settings
  USING (auth.uid() = user_id);

-- ── futures_signals ───────────────────────────────────────────
-- Generated by hot-picks-scanner edge function. Updated by admin or webhook.
CREATE TABLE IF NOT EXISTS futures_signals (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  symbol              text NOT NULL,
  exchange            text,
  full_name           text,
  timeframe           text,
  direction           text CHECK (direction IN ('BUY', 'SELL')),
  confidence          integer,
  entry_zone_min      numeric,
  entry_zone_max      numeric,
  tp1                 numeric,
  tp1_points          numeric,
  tp2                 numeric,
  tp2_points          numeric,
  tp3                 numeric,
  tp3_points          numeric,
  stop_loss           numeric,
  sl_points           numeric,
  risk_reward         text,
  reasoning           jsonb,
  status              text NOT NULL DEFAULT 'ACTIVE'
                      CHECK (status IN ('ACTIVE','TP1_HIT','TP2_HIT','TP3_HIT','STOPPED_OUT','EXPIRED')),
  setup_status        text DEFAULT 'PENDING'
                      CHECK (setup_status IN ('PENDING','AT_ENTRY','MISSED')),
  setup_status_note   text,
  higher_tf_bias      text,
  entry_validation    jsonb,
  current_price       numeric,
  current_pnl_points  numeric,
  session             text DEFAULT 'OFF' CHECK (session IN ('ASIA','LONDON','NY','OFF')),
  atr_value           numeric,
  news_warning        boolean DEFAULT false,
  news_warning_note   text,
  tick_size           numeric,
  tick_value          numeric,
  point_value         numeric,
  contract_size       numeric,
  is_counter_trend    boolean DEFAULT false,
  newbie              jsonb,
  generated_at        timestamptz NOT NULL DEFAULT now(),
  expires_at          timestamptz,
  status_updated_at   timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE futures_signals ENABLE ROW LEVEL SECURITY;

-- NOTE: Elite-only read policy is in CRIT02_rls_tier_enforcement.sql
-- Run that migration too. Service role always has full access.
CREATE POLICY "service role full access signals" ON futures_signals
  USING (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS idx_futures_signals_status ON futures_signals(status);
CREATE INDEX IF NOT EXISTS idx_futures_signals_symbol ON futures_signals(symbol);
CREATE INDEX IF NOT EXISTS idx_futures_signals_generated_at ON futures_signals(generated_at DESC);

-- ── data_analyses ─────────────────────────────────────────────
-- AI chart analysis results from analyze-chart edge function.
-- NOTE: Column names here match the LIVE database and TypeScript types.
-- The original schema.sql had wrong names (confidence_score, entry_price, etc.)
CREATE TABLE IF NOT EXISTS data_analyses (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id             uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  symbol              text NOT NULL,
  timeframe           text,
  direction           text,
  confidence          integer,
  current_price       numeric,
  entry_zone_min      numeric,
  entry_zone_max      numeric,
  stop_loss           numeric,
  sl_points           numeric,
  tp1                 numeric,
  tp1_points          numeric,
  tp2                 numeric,
  tp2_points          numeric,
  tp3                 numeric,
  tp3_points          numeric,
  risk_reward         text,
  higher_tf_bias      text,
  setup_status        text,
  setup_status_note   text,
  is_counter_trend    boolean DEFAULT false,
  reasoning           jsonb,
  entry_validation    jsonb,
  newbie              jsonb,
  outcome             text NOT NULL DEFAULT 'PENDING'
                      CHECK (outcome IN ('PENDING','TP1_HIT','TP2_HIT','TP3_HIT','STOPPED_OUT','SKIPPED')),
  outcome_notes       text,
  outcome_updated_at  timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE data_analyses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users read own analyses" ON data_analyses
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "service role full access analyses" ON data_analyses
  USING (auth.role() = 'service_role');

CREATE INDEX IF NOT EXISTS idx_data_analyses_user_id ON data_analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_data_analyses_created_at ON data_analyses(created_at DESC);

-- ── journal_entries ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS journal_entries (
  id               uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id          uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  analysis_id      uuid REFERENCES data_analyses(id) ON DELETE SET NULL,
  symbol           text NOT NULL,
  timeframe        text,
  direction        text,
  pre_trade_plan   text,
  emotional_state  text CHECK (emotional_state IN ('CONFIDENT','FEARFUL','GREEDY','NEUTRAL','FOMO','DISCIPLINED')),
  followed_plan    boolean,
  entry_notes      text,
  outcome          text NOT NULL DEFAULT 'PENDING'
                   CHECK (outcome IN ('PENDING','TP1_HIT','TP2_HIT','TP3_HIT','STOPPED_OUT','SKIPPED','MISSED')),
  pnl_points       numeric,
  pnl_dollars      numeric,
  post_trade_notes text,
  lessons_learned  text,
  ai_feedback      text,
  ai_feedback_at   timestamptz,
  trade_date       date NOT NULL DEFAULT CURRENT_DATE,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users manage own journal" ON journal_entries
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_journal_user_id ON journal_entries(user_id);
CREATE INDEX IF NOT EXISTS idx_journal_trade_date ON journal_entries(trade_date DESC);

-- ── education_progress ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS education_progress (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id      uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  section_id   text NOT NULL,
  completed    boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  quiz_score   integer,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, section_id)
);

ALTER TABLE education_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users manage own education" ON education_progress
  USING (auth.uid() = user_id);

-- ── quiz_promo_redemptions ────────────────────────────────────
-- Tracks GRADUATE50 promo codes earned via education completion
CREATE TABLE IF NOT EXISTS quiz_promo_redemptions (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id     uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  promo_code  text NOT NULL,
  redeemed    boolean NOT NULL DEFAULT false,
  redeemed_at timestamptz,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

ALTER TABLE quiz_promo_redemptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users read own promos" ON quiz_promo_redemptions
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "service role full access promos" ON quiz_promo_redemptions
  USING (auth.role() = 'service_role');

-- ── admin_notifications ───────────────────────────────────────
-- System alerts surfaced in the admin dashboard (e.g. Yahoo Finance errors)
CREATE TABLE IF NOT EXISTS admin_notifications (
  id         uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  type       text NOT NULL,
  title      text NOT NULL,
  message    text,
  severity   text DEFAULT 'INFO' CHECK (severity IN ('LOW','INFO','HIGH','CRITICAL')),
  read       boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE admin_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admins read notifications" ON admin_notifications
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.is_admin = true)
  );

CREATE POLICY "service role full access notifications" ON admin_notifications
  USING (auth.role() = 'service_role');
